### ISSUE TITLE
向左滑动刷新，松开，cell位置出现了偏移。请指点。

### ISSUE THREAD

**Issue by dfkb2000** [xiezhongmin/XZMRefresh#10]
![snip20161214_8](https://cloud.githubusercontent.com/assets/14798133/21176979/1cc481c4-c224-11e6-9730-1fd61db027b6.png)

**Comment by columbusLGEN** [comment]
当把collectionview 的 pagingEnabled 设为NO 之后不会出现这个问题。
但是我需要设置pagingEnabled为YES 满足分页滑动的需求。

**Comment by dfkb2000** [comment]
解决方法：在主线程让collectionview 滚动到第一个cell（或者最后一个）。
如果之后有朋友使用遇到同样的问题，希望可以帮助到你。

注：该问题与框架本身没有关系。
