### ISSUE TITLE
加左右刷新视图位置错乱

### ISSUE THREAD

**Issue by jxaufang168** [xiezhongmin/XZMRefresh#2]
手动创建一个ViewController  继承UIViewController ，不是继承UICollectionViewController。手动创建UICollectionView，增加左右刷新控件，刷新控件位置错乱。
![1](https://cloud.githubusercontent.com/assets/5266501/13692351/c076ae5c-e77b-11e5-8224-165e9e8fd10e.jpg)
![2](https://cloud.githubusercontent.com/assets/5266501/13692358/ccebacdc-e77b-11e5-8514-34b82b970f4c.jpg)

**Comment by xiezhongmin** [comment]
非常感谢你提供的bug,根据你提供的数据尝试再现bug并没有出现，如果有时间请将demo发给我，谢谢！

**Comment by jxaufang168** [comment]
[DemoViewController.zip](https://github.com/xiezhongmin/XZMRefresh/files/175206/DemoViewController.zip)
把这个DemoViewController 复制到现在这个版本的Demo中，就会出现上面截图的情况。
