### ISSUE TITLE
往左滑动加载更多的时候

### ISSUE THREAD

**Issue by kjxBoy** [xiezhongmin/XZMRefresh#6]
当网络数据返回比较慢的时候回出现没有结束就弹回去的问题

**Comment by xiezhongmin** [comment]
只有掉  // 结束刷新
        [header endRefreshing]; 这个方法才会弹回去，你断点看看，此方法是不是先调了

**Comment by kjxBoy** [comment]
是我layout写的有点问题，已经解决了，谢谢
